project:
  type: website
  output-dir: docs

website:
  title: "Jasbir's Website"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: FYP Project
      - href: extrapage.qmd
        text: Learning Notes
      - href: reflections.qmd
        text: Reflections

format:
  html:
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



